# Generated by Django 4.1.1 on 2022-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="projects.tag"),
        ),
    ]
