# Generated by Django 4.1.1 on 2022-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
